name: pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=hd77b12b_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.74.0=h5b4e17d_6
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py310hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2024.6.2=h56e8100_0
  - cairo=1.16.0=haedb8bc_5
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2bbff1b_0
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=py310haa95532_0
  - cryptography=41.0.7=py310h89fc84f_0
  - cuda-cccl=12.1.109=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=hd77b12b_0
  - cytoolz=0.12.2=py310h2bbff1b_0
  - dask-core=2024.5.2=pyhd8ed1ab_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - eigen=3.4.0=h2d74725_0
  - expat=2.6.2=h63175ca_0
  - filelock=3.13.1=py310haa95532_0
  - fontconfig=2.14.1=h9c4af85_2
  - freetype=2.12.1=ha860e81_0
  - freexl=1.0.6=h2bbff1b_0
  - fsspec=2024.6.0=pyhff2d567_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_1
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - grad-cam=1.5.2=pyhd8ed1ab_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - huggingface_hub=0.23.3=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - imagecodecs=2023.1.23=py310h6c6a46e_0
  - imageio=2.34.1=pyh4b66e23_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.5.0=py310haa95532_0
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libavif=0.11.1=h2bbff1b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=12.0.0=default_h627e005_2
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcurl=8.7.1=h86230a5_0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.4=hd77b12b_0
  - libgdal=3.6.2=h676b171_3
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.17=h8ffe710_0
  - libkml=1.3.0=h9859afa_1014
  - libnetcdf=4.8.1=h6685c40_4
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialite=4.3.0a=h6ec8781_23
  - libssh2=1.11.0=h291bd65_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_2
  - libxslt=1.1.37=h2bbff1b_1
  - libzip=1.8.0=h289538f_1
  - libzopfli=1.0.3=h0e60522_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.3=py310h2bbff1b_0
  - matplotlib-base=3.4.3=py310h79a7439_2
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - networkx=3.1=py310haa95532_0
  - numpy=1.26.3=py310h055cbcc_0
  - numpy-base=1.26.3=py310h65a83cf_0
  - opencv=4.6.0=py310ha7641e4_2
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_2
  - packaging=23.1=py310haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=10.0.1=py310h045eedc_0
  - pip=23.3.1=py310haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=3.10.0=py310haa95532_0
  - poppler=22.12.0=h0bf3bde_3
  - poppler-data=0.4.12=hd8ed1ab_0
  - proj=6.2.1=h3758d61_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310haa95532_1
  - pyopenssl=23.2.0=py310haa95532_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.5.0=py310h9128911_0
  - pyyaml=6.0=py310he2412df_4
  - pyzmq=25.1.0=py310hd77b12b_0
  - qhull=2020.2=h70d2c02_2
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - requests=2.31.0=py310haa95532_0
  - safetensors=0.4.2=py310h0010962_0
  - scikit-image=0.19.3=py310hd77b12b_1
  - setuptools=68.2.2=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6c2663c_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tifffile=2023.2.28=pyhd8ed1ab_0
  - tiledb=2.3.3=hd8964de_3
  - timm=1.0.3=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - ttach=0.0.3=pyhd8ed1ab_0
  - typing-extensions=4.12.1=hd8ed1ab_0
  - typing_extensions=4.12.1=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xerces-c=3.2.4=hd77b12b_1
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=hd77b12b_0
  - zfp=1.0.0=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.2.1
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - comm==0.1.3
    - contourpy==1.0.7
    - cuda-python==12.1.0
    - cycler==0.11.0
    - cython==0.29.35
    - defusedxml==0.7.1
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - fonttools==4.40.0
    - gdown==5.2.0
    - glob2==0.7
    - ipykernel==6.23.2
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - jedi==0.18.2
    - joblib==1.2.0
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-events==0.6.3
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - matplotlib==3.7.1
    - mistune==2.0.5
    - natsort==8.4.0
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.4.0
    - nbformat==5.9.0
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - overrides==7.3.1
    - pandas==2.0.2
    - pandocfilters==1.5.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pywin32==306
    - pywinpty==2.0.10
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.5.0
    - scipy==1.10.1
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - tzdata==2023.3
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - websocket-client==1.5.3
    - widgetsnbextension==4.0.7
prefix: C:\Users\mhasson\Anaconda3\envs\pytorch
